/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as rootRootRouteImport } from './routes/(root)/_root'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as rootRootIndexRouteImport } from './routes/(root)/_root.index'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth.login'

const rootRootRoute = rootRootRouteImport.update({
  id: '/(root)/_root',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const rootRootIndexRoute = rootRootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRootRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authAuthLoginRoute
  '/': typeof rootRootIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authAuthLoginRoute
  '/': typeof rootRootIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(root)/_root': typeof rootRootRouteWithChildren
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(root)/_root/': typeof rootRootIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/'
  id:
    | '__root__'
    | '/(auth)/_auth'
    | '/(root)/_root'
    | '/(auth)/_auth/login'
    | '/(root)/_root/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
  rootRootRoute: typeof rootRootRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(root)/_root': {
      id: '/(root)/_root'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/_root/': {
      id: '/(root)/_root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootRootIndexRouteImport
      parentRoute: typeof rootRootRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface rootRootRouteChildren {
  rootRootIndexRoute: typeof rootRootIndexRoute
}

const rootRootRouteChildren: rootRootRouteChildren = {
  rootRootIndexRoute: rootRootIndexRoute,
}

const rootRootRouteWithChildren = rootRootRoute._addFileChildren(
  rootRootRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
  rootRootRoute: rootRootRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
