/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as rootRootRouteImport } from './routes/(root)/_root'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as rootRootIndexRouteImport } from './routes/(root)/_root.index'
import { Route as rootRootTicketsRouteImport } from './routes/(root)/_root.tickets'
import { Route as rootRootNetworkRouteImport } from './routes/(root)/_root.network'
import { Route as rootRootInventoryRouteImport } from './routes/(root)/_root.inventory'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth.login'

const rootRootRoute = rootRootRouteImport.update({
  id: '/(root)/_root',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const rootRootIndexRoute = rootRootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRootRoute,
} as any)
const rootRootTicketsRoute = rootRootTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRootRoute,
} as any)
const rootRootNetworkRoute = rootRootNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRootRoute,
} as any)
const rootRootInventoryRoute = rootRootInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRootRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authAuthLoginRoute
  '/inventory': typeof rootRootInventoryRoute
  '/network': typeof rootRootNetworkRoute
  '/tickets': typeof rootRootTicketsRoute
  '/': typeof rootRootIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authAuthLoginRoute
  '/inventory': typeof rootRootInventoryRoute
  '/network': typeof rootRootNetworkRoute
  '/tickets': typeof rootRootTicketsRoute
  '/': typeof rootRootIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(root)/_root': typeof rootRootRouteWithChildren
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(root)/_root/inventory': typeof rootRootInventoryRoute
  '/(root)/_root/network': typeof rootRootNetworkRoute
  '/(root)/_root/tickets': typeof rootRootTicketsRoute
  '/(root)/_root/': typeof rootRootIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/inventory' | '/network' | '/tickets' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/inventory' | '/network' | '/tickets' | '/'
  id:
    | '__root__'
    | '/(auth)/_auth'
    | '/(root)/_root'
    | '/(auth)/_auth/login'
    | '/(root)/_root/inventory'
    | '/(root)/_root/network'
    | '/(root)/_root/tickets'
    | '/(root)/_root/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthRoute: typeof authAuthRouteWithChildren
  rootRootRoute: typeof rootRootRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(root)/_root': {
      id: '/(root)/_root'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/_root/': {
      id: '/(root)/_root/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootRootIndexRouteImport
      parentRoute: typeof rootRootRoute
    }
    '/(root)/_root/tickets': {
      id: '/(root)/_root/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof rootRootTicketsRouteImport
      parentRoute: typeof rootRootRoute
    }
    '/(root)/_root/network': {
      id: '/(root)/_root/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof rootRootNetworkRouteImport
      parentRoute: typeof rootRootRoute
    }
    '/(root)/_root/inventory': {
      id: '/(root)/_root/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof rootRootInventoryRouteImport
      parentRoute: typeof rootRootRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface rootRootRouteChildren {
  rootRootInventoryRoute: typeof rootRootInventoryRoute
  rootRootNetworkRoute: typeof rootRootNetworkRoute
  rootRootTicketsRoute: typeof rootRootTicketsRoute
  rootRootIndexRoute: typeof rootRootIndexRoute
}

const rootRootRouteChildren: rootRootRouteChildren = {
  rootRootInventoryRoute: rootRootInventoryRoute,
  rootRootNetworkRoute: rootRootNetworkRoute,
  rootRootTicketsRoute: rootRootTicketsRoute,
  rootRootIndexRoute: rootRootIndexRoute,
}

const rootRootRouteWithChildren = rootRootRoute._addFileChildren(
  rootRootRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authAuthRoute: authAuthRouteWithChildren,
  rootRootRoute: rootRootRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
